#!/bin/bash

# vim: ft=sh :

# BEGIN-INCLUDE LICENSE.header
# END-INCLUDE
# BEGIN-INCLUDE src/shlog.bash
# END-INCLUDE
# BEGIN-INCLUDE src/shlog-dump.bash
# END-INCLUDE
# BEGIN-INCLUDE src/shlog-init.bash
# END-INCLUDE
# BEGIN-INCLUDE src/shlog-selfdebug.bash
# END-INCLUDE

# detect if being sourced and
# export if so else execute
# main function with args
shlog-init
if [[ ${BASH_SOURCE[0]} != $0 ]]; then
    export -f shlog shlog-dump
else
    shlog "${@}"
fi
