.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SHLOG" "1" "June 2016" "" ""
.
.SH "NAME"
\fBshlog\fR \- Easy logging for the shell
.
.P
fewew
.
.SH "SYNOPSIS"
\fBshlog \-l debug "I\'m a debug message"\fR
.
.P
[debug] 2016\-06\-19 23:47:36 shlog\.sh:8 \- I\'m a debug message"
.
.P
\fBSOMEVAR=3 shlog \-l info \-d SOMEVAR\fR
.
.P
[info] 2016\-06\-19 23:47:36 shlog\.sh:10 \- SOMEVAR=\'3\'
.
.SH "USAGE"
.
.SH "CONFIGURATION"
.
.SS "Log levels"
\fBshlog\fR knows five levels, from lowest to highest priority:
.
.IP "\(bu" 4
trace
.
.IP "\(bu" 4
debug
.
.IP "\(bu" 4
info
.
.IP "\(bu" 4
warn
.
.IP "\(bu" 4
error
.
.IP "" 0
.
.SS "Configuration files"
\fBshlog\fR will look in three places for a configuration file with environment variables:
.
.IP "\(bu" 4
\fB/etc/default/shlogrc\fR
.
.IP "\(bu" 4
\fB$HOME/\.config/shlog/shlogrc\fR
.
.IP "\(bu" 4
\fB$PWD/\.shlogrc\fR
.
.IP "" 0
.
.P
Environment variables in any of those files will be sourced in that order to configure the logging\.
.
.SS "Colors"
Defines the colors to use for various part of the log message if \fI\fBSHLOG_USE_STYLES\fR\fR is set for that \fIoutput\fR\.
.
.P
\fBSHLOG_STYLE_TRACE\fR : \fB%level\fR==\fBtrace\fR : Default: magenta
.
.P
\fBSHLOG_STYLE_DEBUG\fR : \fB%level\fR==\fBdebug\fR : Default: cyan
.
.P
\fBSHLOG_STYLE_INFO\fR : \fB%level\fR==\fBinfo\fR : Default: cyan
.
.P
\fBSHLOG_STYLE_WARN\fR : \fB%level\fR==\fBwarn\fR : Default: yellow
.
.P
\fBSHLOG_STYLE_ERROR\fR : \fB%level\fR==\fBerror\fR : Default: bold red
.
.P
\fBSHLOG_STYLE_MODULE\fR : \fB%module\fR : Default: bold
.
.P
\fBSHLOG_STYLE_LINE\fR : \fB%line\fR : Default: bold green
.
.P
\fBSHLOG_STYLE_DATE\fR : \fB%date\fR : Default: none
.
.P
\fBSHLOG_STYLE_RESET\fR : (after every style) : Default: \fB[0m\fR
.
.SS "Outputs"
Defines the minimum level at which to log to different outputs
.
.P
\fBSHLOG_TERM\fR: Minimum level for terminal\. Default: \fBtrace\fR
.
.P
\fBSHLOG_FILE\fR: Minimum level for file logging\. Default: \fBoff\fR
.
.SS "Enabling / Disabling colors"
Defines which outputs should use \fIstyles\fR\.
.
.P
\fBSHLOG_TERM_COLORIZE\fR: Use styles on terminal \. Default: \fB"true"\fR
.
.P
\fBSHLOG_FILE_COLORIZE\fR: Use styles on file \. Default: \fB"false"\fR
.
.SS "Term Output options"
.
.P
Whether to output to \fBstderr\fR (the default) or \fBstdout\fR\.
.
.SS "File Output options"
.
.P
\fBSHLOG_FILE_FILENAME\fR: Filename of the file to log to\.
.
.P
Default: basename of \fB$0\fR with out extension + \fB\.log\fR in \fB/tmp\fR
.
.SS "Formatting Log output"
.
.P
\fBstrftime(3)\fR pattern for the \fB%date\fR part of a log message, to be passed to \fBprintf\fR\.
.
.P
Default: \fB%(%F %T)T\fR (i\.e\. \fBYYYY\-MM\-DD HH:MM:SS\fR)
.
.P
\fBprintf\fR\-Pattern for the log message\.
.
.P
Default: \fB[%level] %date %module:%line \- %msg\fR
.
.P
Custom patterns:
.
.P
\fB%level\fR: The \fIlog level\fR
.
.P
\fB%date\fR: The timestamp of the log message, see \fI\fBSHLOG_DATE_FORMAT\fR\fR
.
.P
\fB%module\fR: The calling \fImodule\fR
.
.P
\fB%line\fR: Line number of the calling script
.
.P
\fB%msg\fR: The actual log message
.
.SS "Debugging shlog"
.
.P
If set to \fB"true"\fR, shlog will output its configuration upon first initialization\.
.
.P
Default: false
.
.SH "FAQ"
.
.SS "How to turn off logging?"
Set the \fBSHLOG_SILENT\fR variable to a non\-zero value to discard all log messages within that shell:
.
.IP "" 4
.
.nf

SHLOG_SILENT=true some\-noisy\-script\.sh
.
.fi
.
.IP "" 0
.
.SS "How to debug the logging?"
To debug the logging process itself, set the \fBSHLOG_SELFDEBUG\fR variable to a non zero value:
.
.IP "" 4
.
.nf

SHLOG_SELFDEBUG=true some\-command\.sh
.
.fi
.
.IP "" 0
.
.P
This will make \fBshlog\fR output its configuration upon initialization and also log all the files it sourced\.
.
.SS "How to log to STDOUT instead of STDERR?"
Set \fBSHLOG_TERM_OUTPUT\fR to \fBstdout\fR:
.
.IP "" 4
.
.nf

SHLOG_TERM_OUTPUT=stdout
SHLOG_TERM=debug # or trace, info, warn, error
.
.fi
.
.IP "" 0
.
.SS "How to log to a file?"
Enable the \fBfile\fR output in your \fIconfiguration file\fR:
.
.IP "" 4
.
.nf

SHLOG_FILE=trace
SHLOG_FILE_FILENAME=$PWD/myscrip\.log
.
.fi
.
.IP "" 0
.
.P
\fBSHLOG_FILE_FILENAME\fR is optional, will default to a file in /tmp derived from $0 if not set explicitly
.
.SS "How to enable or disable color output?"
Define \fBSHLOG_<output>_COLORIZE\fR\. The default is:
.
.IP "" 4
.
.nf

SHLOG_TERM_COLORIZE=true
SHLOG_FILE_COLORIZE=false
.
.fi
.
.IP "" 0
.
.SS "Logging is slow and <code>module</code> is always <code>shlog</code>?"
While you can use \fBshlog\fR as a command line script, it\'s much faster to use it as a shell function\.
.
.P
Make sure you \fBsource\fR the \fBshlog\fR script, otherwise every log command is spawning a new shell\. Compare:
.
.P
Slow:
.
.IP "" 4
.
.nf

time for i in $(seq 1000); do shlog \-l info test; done
# \.\.\.
# real  0m4\.466s
# user  0m0\.164s
# sys   0m0\.172s
.
.fi
.
.IP "" 0
.
.P
Fast:
.
.IP "" 4
.
.nf

source "$(which shlog)"
time for i in $(seq 1000); do shlog \-l info test; done
# \.\.\.
# real  0m0\.889s
# user  0m0\.408s
# sys   0m0\.136s
.
.fi
.
.IP "" 0
.
.SS "<code>shlog</code> doesn\'t respect my configuration?"
.
.SS "How to reload the configuration?"
Call \fBshlog::reload\fR, without any arguments\. It will reconfigure all variables and all changes should be visible then\.
.
.SH "COPYRIGHT"
The MIT License (MIT)
.
.P
Copyright (c) 2016 Konstantin Baierer
.
.P
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.
.P
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\.
.
.P
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\.
